services:
  test-mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: test-mailserver
    hostname: testmail.local
    ports:
      - "1143:143"   # IMAP (non-SSL for local testing)
      - "1025:25"    # SMTP
      - "1993:993"   # IMAP SSL
      - "1587:587"   # SMTP Submission
    environment:
      - ENABLE_IMAP=1
      - ENABLE_POP3=0
      - ENABLE_CLAMAV=0
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_POSTGREY=0
      - SSL_TYPE=
      - ONE_DIR=1
      - DMS_DEBUG=0
    volumes:
      - ./test-mail-data:/var/mail
      - ./test-mail-config:/tmp/docker-mailserver
    cap_add:
      - NET_ADMIN