services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: aiemailuser
      POSTGRES_PASSWORD: aiemailpass
      POSTGRES_DB: aiemaildb
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aiemailuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__LOG_LEVEL=INFO
    # Health check disabled - container doesn't have curl/wget
    # API is accessible at http://localhost:6333/

volumes:
  postgres_data:
  redis_data: