version: '3.8'

services:
  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    ports:
      - "8888:80"  # Access webmail at http://localhost:8888
    environment:
      # Database configuration (using SQLite for simplicity)
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      
      # IMAP configuration - connect to your test mail server
      # Using host.docker.internal to connect to localhost from within container
      - ROUNDCUBEMAIL_DEFAULT_HOST=host.docker.internal
      - ROUNDCUBEMAIL_DEFAULT_PORT=1143
      
      # SMTP configuration
      - ROUNDCUBEMAIL_SMTP_SERVER=host.docker.internal
      - ROUNDCUBEMAIL_SMTP_PORT=1025
      
      # UI configuration
      - ROUNDCUBEMAIL_SKIN=elastic
      
      # Plugins
      - ROUNDCUBEMAIL_PLUGINS=archive,zipdownload
      
      # Auto-add domain to username if not provided
      - ROUNDCUBEMAIL_USERNAME_DOMAIN=testmail.local
      
      # Security settings for test environment
      - ROUNDCUBEMAIL_IMAP_CONN_OPTIONS=ssl://verify_peer=false;ssl://verify_peer_name=false
      - ROUNDCUBEMAIL_SMTP_CONN_OPTIONS=ssl://verify_peer=false;ssl://verify_peer_name=false
      
    volumes:
      # Persist SQLite database
      - ./roundcube/db:/var/roundcube/db
      # Custom config - mount directly to where Roundcube expects it
      - ./roundcube/config/custom.config.inc.php:/var/www/html/config/custom.config.inc.php:ro
    
    # Only needed on Mac/Windows to access host's localhost
    extra_hosts:
      - "host.docker.internal:host-gateway"